PRODUCTION: true
PORT: "8080"
## Redis configuration
REDIS_URL: "localhost:6379"
REDIS_PASSWORD: "password"

## MySQL configuration
MYSQL_URI: "root:@tcp(localhost:3306)/go_practice?charset=utf8mb4&parseTime=True&loc=Local"
